version: '3.8'

services:
  cow-webui:
    image: harrison7/cow-webui:latest  # 替换为你的 DockerHub 用户名和镜像名
    ports:
      - "5173:80"  # 映射容器的 80 端口到主机的 80 端口  # 如果后端服务需要直接访问，也映射 5002 端口
    environment:
      - SECRET_KEY=your_secret_key_here  # 替换为你的实际密钥
      - CORS_ORIGINS=http://localhost  # 根据需要设置 CORS
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # 如果需要在容器内管理 Docker
      - cow_data:/app/data  # 持久化数据存储
      - cow_logs:/app/backend/logs 
    restart: always

volumes:
  cow_data:  # 定义持久化卷
  cow_logs:  # 添加这一行