version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: {{service_name}}
    security_opt:
      - seccomp:unconfined
    environment:
      TZ: 'Asia/Shanghai'
      MODEL: '{{MODEL}}'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '{{SINGLE_CHAT_PREFIX}}'
      SINGLE_CHAT_REPLY_PREFIX: '{{SINGLE_CHAT_REPLY_PREFIX}}'
      GROUP_CHAT_PREFIX: '{{GROUP_CHAT_PREFIX}}'
      GROUP_NAME_WHITE_LIST: '{{GROUP_NAME_WHITE_LIST}}'
      IMAGE_CREATE_PREFIX: '["画"]'
      CONVERSATION_MAX_TOKENS: '{{CONVERSATION_MAX_TOKENS}}'
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '{{CHARACTER_DESC}}'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
      TEMPERATURE: '{{TEMPERATURE}}'
      # 环境变量将在这里动态添加
